#!/bin/sh

# This helper script is used by buildbot. It runs autoreconf and configure
# if they are needed.
# 
# Normally, running "make" would be enough, since automake Makefiles check
# if the configure script needs to be run or generated again. However, there
# is a bootstrap problem: the first time buildbot tries to compile on a
# buildslave, or if it has to clean the source directory for some reason,
# there will be no Makefile at all, so "make" would fail.

set -e

run_configure() {
    rm -f config.args
    echo "Running configure..."
    ./configure "$@"
    echo "$*" > config.args
}

if [ ! -f Makefile ]; then

    if [ ! -f configure ]; then
        echo "configure missing."

        echo "Running autoreconf..."
        autoreconf -i
    else
        echo "Makefile missing."
    fi

    run_configure "$@"

elif [ ! -f config.args ] || [ "`cat config.args`" != "$*" ]; then

    echo "configure flags changed."

    run_configure "$@"

else
    if make -q Makefile; then
        echo "Nothing to do."
    else
        make Makefile
    fi
fi
