#!/bin/sh

# This helper script is used by buildbot. It runs autoreconf and configure
# if they are needed.
# 
# Normally, running "make" would be enough, since automake Makefiles check
# if the configure script needs to be run or generated again. However, there
# is a bootstrap problem: the first time buildbot tries to compile on a
# buildslave, or if it has to clean the source directory for some reason,
# there will be no Makefile at all, so "make" would fail.

if [ ! -f Makefile ]; then

    if [ ! -f configure ]; then
        echo "configure missing."

        echo "Running autoreconf..."
        autoreconf -i
    else
        echo "Makefile missing."
    fi

    echo "$*" > config.args;
    echo "Running configure..."
    ./configure "$@"

elif [ ! -f config.args ] || [ "`cat config.args`" != "$*" ]; then

    echo "configure flags changed."

    echo "$*" > config.args;
    echo "Running configure..."
    ./configure "$@"

else

    echo "Nothing to do."

fi
