## -*-Makefile -*-
## $Id: Makefile.incl 14918 2008-03-15 03:26:14Z repr $

PTHREAD_CFLAGS = @PTHREAD_CFLAGS@
PTHREAD_LIBS = @PTHREAD_LIBS@

RSA_LIBS = -lcrypto

AM_CPPFLAGS =                  \
        -I$(top_srcdir)        \
        -I$(top_srcdir)/lib    \
        -I$(top_srcdir)/client

# dependencies to make sure libs gets compiled before
# programs linking to them:

LIBBOINC = $(top_builddir)/lib/libboinc.a
$(LIBBOINC):
	cd $(top_builddir)/lib; ${MAKE} libboinc.a
