# - Try to find the UnitTest++ library

FIND_PATH(UNITTESTPP_INCLUDE_DIR UnitTest++.h PATH_SUFFIXES unittest++)
FIND_LIBRARY(UNITTESTPP_LIBRARY UnitTest++)

INCLUDE(FindPackageHandleStandardArgs)

# handle the QUIETLY and REQUIRED arguments and set UNITTESTPP_FOUND to TRUE if
# all listed variables are TRUE
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UnitTestPP DEFAULT_MSG UNITTESTPP_INCLUDE_DIR UNITTESTPP_LIBRARY)

MARK_AS_ADVANCED(UNITTESTPP_INCLUDE_DIR UNITTESTPP_LIBRARY)

if(UNITTESTPP_FOUND)
    set(UNITTESTPP_INCLUDE_DIRS ${UNITTESTPP_INCLUDE_DIR})
    set(UNITTESTPP_LIBRARIES    ${UNITTESTPP_LIBRARY})
endif(UNITTESTPP_FOUND)
